project:
  type: manuscript
  output-dir: _site

website:
  title: "Machine Learning For Microscopy"
  site-url: https://YOUR_GITHUB_USERNAME.github.io/MachineLearningForMicroscopy
  repo-url: https://github.com/YOUR_GITHUB_USERNAME/MachineLearningForMicroscopy

execute:
  freeze: auto

format:
  html:
    css: styles.css
    fontsize: 14pt
    email-obfuscation: javascript
    theme: darkly  
    toc: true
    comments:
      hypothesis: false
  docx: default





