project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    css: styles.css
    fontsize: 14pt
    email-obfuscation: javascript
    theme: darkly  
    toc: true
    comments:
      hypothesis: false
  docx: default





